name: date_time_picker_form_field
description: Date and Time picker that uses Futters FormField and Decoration.
version: 0.0.2
homepage: https://github.com/LeonardoJRibeiro/date_time_form_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
